### ISSUE TITLE
https://wordpress.org/plugins/fancybox-for-wordpress/#description -> The link to the demo needs to be changed 

### ISSUE THREAD

**Issue by ViSi19** [WPChill/fancybox-for-wordpress#12]
If you click on this section "this blog": https://gyazo.com/663bb968236260a68bceff05d251e9be then it will redirect you to a page that does not work. 
https://wordpress.org/plugins/fancybox-for-wordpress/#description

**Comment by razvanaldea89** [comment]
@ViSi19 This should be moved to https://github.com/ColorlibHQ/fancybox-for-wordpress not here
